name: test

on:
  push:
  pull_request:

jobs:
  plugin_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ver: [0.6.0, 0.5.1]

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          version: ${{ matrix.ver }}
          command: ko version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
