name: CI

on:
  push:
    branches:
      - main

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: ko version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
